blueprint:
  name: Motion Light – Day/Night (UI Controls)
  description: Motion-activated lights with separate day/night brightness.
  domain: automation

  input:
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    light_target:
      name: Light or Area
      selector:
        target:

    day_brightness:
      name: Day Brightness (%)
      default: 100
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    night_brightness:
      name: Night Brightness (%)
      default: 25
      selector:
        number:
          min: 1
          max: 100
          unit_of_measurement: "%"

    off_delay:
      name: Off Delay
      default: "00:05:00"
      selector:
        duration:

mode: restart

trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"

action:
  - choose:
      - conditions:
          - condition: sun
            after: sunset
            before: sunrise
        sequence:
          - service: light.turn_on
            target: !input light_target
            data:
              brightness_pct: !input night_brightness
    default:
      - service: light.turn_on
        target: !input light_target
        data:
          brightness_pct: !input day_brightness

  - wait_for_trigger:
      - platform: state
        entity_id: !input motion_sensor
        from: "on"
        to: "off"

  - delay: !input off_delay

  - service: light.turn_off
    target: !input light_target
