blueprint:
  name: Motion Light – Day/Night Settings
  description: >
    Turn lights on when motion is detected.
    Uses different light settings during daytime vs night (sunset to sunrise),
    then turns lights off after motion stops and a delay.
  domain: automation

  input:
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    light_target:
      name: Light or Area
      selector:
        target:

    day_light_data:
      name: Day Light Settings
      description: Light.turn_on service data for daytime
      selector:
        object:

    night_light_data:
      name: Night Light Settings
      description: Light.turn_on service data for nighttime
      selector:
        object:

    off_delay:
      name: Off Delay
      default: "00:05:00"
      selector:
        duration:

    sunset_offset:
      name: Sunset Offset
      default: "00:05:00"
      selector:
        duration:

    sunrise_offset:
      name: Sunrise Offset
      default: "00:30:00"
      selector:
        duration:

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"

action:
  - choose:
      - conditions:
          - condition: sun
            after: sunset
            after_offset: !input sunset_offset
            before: sunrise
            before_offset: !input sunrise_offset
        sequence:
          - service: light.turn_on
            target: !input light_target
            data: !input night_light_data
    default:
      - service: light.turn_on
        target: !input light_target
        data: !input day_light_data

  - wait_for_trigger:
      - platform: state
        entity_id: !input motion_sensor
        from: "on"
        to: "off"

  - delay: !input off_delay

  - service: light.turn_off
    target: !input light_target