blueprint:
  name: Motion-Activated Light (Day/Night Settings)
  description: >
    Turn on lights when motion is detected, using different brightness/color/effect
    during daytime vs between sunset and sunrise. Turns lights off after motion stops
    and a configurable delay.
  domain: automation

  input:
    motion_sensor:
      name: Motion Sensor
      selector:
        entity:
          domain: binary_sensor
          device_class: motion

    target_light:
      name: Light or Area
      description: Select either a light entity or an area
      selector:
        target:
          entity:
            domain: light
          area: {}

    day_settings:
      name: Day Light Settings
      selector:
        light:

    night_settings:
      name: Night Light Settings
      selector:
        light:

    off_delay:
      name: Delay Before Turning Off
      description: Time to wait after motion stops
      default: "00:05:00"
      selector:
        duration:

    sunset_offset:
      name: Sunset Offset
      default: "00:05:00"
      selector:
        duration:

    sunrise_offset:
      name: Sunrise Offset
      default: "00:30:00"
      selector:
        duration:

mode: restart
max_exceeded: silent

trigger:
  - platform: state
    entity_id: !input motion_sensor
    from: "off"
    to: "on"

action:
  - choose:
      - conditions:
          - condition: sun
            after: sunset
            after_offset: !input sunset_offset
            before: sunrise
            before_offset: !input sunrise_offset
        sequence:
          - service: light.turn_on
            target: !input target_light
            data: !input night_settings
    default:
      - service: light.turn_on
        target: !input target_light
        data: !input day_settings

  - wait_for_trigger:
      - platform: state
        entity_id: !input motion_sensor
        from: "on"
        to: "off"

  - delay: !input off_delay

  - service: light.turn_off
    target: !input target_light