blueprint:
  name: Randomize Group Colors (manual / callable)
  description: >
    Randomizes each light within a selected light group to a randomly chosen
    color from your predefined color pool. Each light gets its own random pick.
    This blueprint is intentionally triggerless — run it manually or call it
    from another automation (example scheduler provided below).
  domain: automation

  input:
    target_group:
      name: Light group
      description: Select the light group whose lights will be randomized.
      selector:
        entity:
          domain: light
    color_pool:
      name: Color pool
      description: >
        Comma-separated list of colors. Use color names (red, blue, white)
        or JSON-style RGB lists like [255, 0, 0]. Example: red, white, [0,0,255]
      default: "red, white, blue"
      selector:
        text:
    only_if_on:
      name: Only randomize lights that are currently ON
      description: If enabled, lights that are off will be skipped.
      default: true
      selector:
        boolean: {}

# no trigger here — the automation created from this blueprint is meant to be run manually
variables:
  color_pool_list: "{{ color_pool.split(',') | map('trim') | list }}"
  target_lights: "{{ expand(target_group) }}"

mode: restart

action:
  - variables:
      pool: "{{ color_pool_list }}"
      only_on_flag: "{{ only_if_on | bool }}"
  - repeat:
      for_each: "{{ target_lights }}"
      sequence:
        - condition: template
          # Skip lights that are off when only_if_on is true
          value: >
            {% if only_on_flag %}
              {{ repeat.item.state == 'on' }}
            {% else %}
              true
            {% endif %}
        - variables:
            chosen_color: "{{ pool | random }}"
        - choose:
            - conditions:
                - "{{ chosen_color.startswith('[') }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item.entity_id }}"
                  data:
                    rgb_color: "{{ chosen_color | from_json }}"
                    brightness: 255
            - default:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item.entity_id }}"
                  data:
                    color_name: "{{ chosen_color }}"
                    brightness: 255
