blueprint:
  name: Randomize Group Colors (fixed trigger)
  description: >
    Randomizes each light within a selected light group to a randomly chosen
    color from your predefined color pool. Each light gets its own random pick.
    This version avoids templating inside the trigger by using a 1s time_pattern
    and gating execution in the action (so manual runs still work).
  domain: automation
  input:
    target_group:
      name: Light Group
      selector:
        entity:
          domain: light
    color_pool:
      name: Color Pool
      description: >
        Enter a comma-separated list of colors. Use color names (red, blue, white)
        or RGB lists like [255, 0, 0]. Example: red, white, [0,0,255]
      default: "red, white, blue"
      selector:
        text:
    interval:
      name: Randomization Interval (seconds)
      description: >
        How often to apply new random colors. Leave at 0 for manual-only mode
        (run on demand from the automation UI).
      default: 0
      selector:
        number:
          min: 0
          max: 86400
          unit_of_measurement: seconds

mode: restart

# This fires every second. Execution is gated in the action below so:
# - If interval = 0, only manual runs (from UI) will proceed.
# - If interval > 0, execution only proceeds when the current timestamp
#   is divisible by the interval (so it runs roughly every N seconds).
trigger:
  - platform: time_pattern
    seconds: "/1"

variables:
  # normalize color pool into a list of trimmed strings
  color_pool_list: >
    {{ color_pool.split(',') | map('trim') | list }}
  target_lights: "{{ expand(target_group) }}"
  int_interval: "{{ interval | int }}"

action:
  # gate: decide whether this execution should proceed
  - condition: template
    # If interval == 0, only allow non-time_pattern triggers (manual runs).
    # If interval > 0, only allow when as_timestamp(now()) % interval == 0.
    value: >
      {% set intv = int_interval | int %}
      {% if intv == 0 %}
        {{ trigger is not defined or (trigger is defined and trigger.platform != 'time_pattern') }}
      {% else %}
        {{ (as_timestamp(now()) | int) % intv == 0 }}
      {% endif %}

  # If we passed the gate, randomize each light
  - repeat:
      for_each: "{{ target_lights }}"
      sequence:
        - variables:
            chosen_color: "{{ color_pool_list | random }}"
        - choose:
            - conditions:
                # detect an RGB list string like "[255, 0, 0]"
                - "{{ chosen_color.startswith('[') }}"
              sequence:
                - service: light.turn_on
                  target:
                    entity_id: "{{ repeat.item.entity_id }}"
                  data:
                    rgb_color: "{{ chosen_color | from_json }}"
                    brightness: 255
          default:
            - service: light.turn_on
              target:
                entity_id: "{{ repeat.item.entity_id }}"
              data:
                color_name: "{{ chosen_color }}"
                brightness: 255
